export enum CookieName {
  playerId = "playerId",
  currentAnswer = "currentAnswer",
  answerTypeChoice = "answerTypeChoice",
  playersAnswers = "playersAnswers",
  duoAnswersIndexes = "duoAnswersIndexes",
  questionsRecord = "questionsRecord",
  caPasseOuCaCashMaster = "caPasseOuCaCashMaster",
  kidimieuxMaster = "kidimieuxMaster",
  buzzAnswerTypeChoice = "buzzAnswerTypeChoice",
  playersBuzz = "playersBuzz",
  scubaDiversNumbers = "scubaDiversNumbers",
  racePlayersAnswers = "racePlayersAnswers",
  scubaCurrentIndex = "scubaCurrentIndex",
  scubaRanking = "scubaRanking",
  scubadoobidooState = "scubadoobidooState",
}
