export enum Sounds {
  homeWater = "/sounds/Home-water.mp3",
  gamePrep = "/sounds/GamePrep.mp3",
  CPOCCJingle = "/sounds/CaPasseOuCaCash.mp3",
  playerAdded = "/sounds/PlayerAdded.mp3",
  firstCash = "/sounds/FirstCash.mp3",
  cash = "/sounds/Cash.mp3",
  carre = "/sounds/Carre.mp3",
  duo = "/sounds/Duo.mp3",
  wrong = "/sounds/Wrong.mp3",
  gameStart = "/sounds/GameStart.mp3",
  quizOver = "/sounds/QuizOver.mp3",
  quizBackground = "/sounds/QuizBackground.mp3",
  topScreensBackground = "/sounds/TopScreensBackground.mp3",
  topScreensBackgroundStart = "/sounds/TopScreensBackgroundStart.mp3",
  topScreenTransition = "/sounds/TopScreenTransition.mp3",
  screensTransition = "/sounds/ScreensTransition.mp3",
}
